# Generated by Django 5.2.3 on 2025-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="dob",
            field=models.DateField(blank=True),
        ),
    ]
