# Generated by Django 5.2.3 on 2025-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_members_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
