# Generated by Django 5.2.3 on 2025-07-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_members_dob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="members",
            options={"ordering": ["-created"]},
        ),
    ]
