# Generated by Django 5.2.3 on 2025-07-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_membership_members_add_on_services_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="approved",
            field=models.CharField(
                choices=[("approved", "Approved"), ("not approved", "Not Approved")],
                default="not approved",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="final_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
